# Generated by Django 5.1 on 2024-09-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
