# Generated by Django 5.1 on 2024-09-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop_booking', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
    ]
